#!/bin/bash

function print_usage(){
  echo "this is ava!"
}

function ssh_server(){
  if [ "$1" = "0" ]; then
  	ssh ray@123.57.54.83
  elif [ "$1" = "1" ]; then
    ssh -p 2220 ray@192.168.74.251
  elif [ "$1" = "2" ]; then
  	ssh -p 2221 ray@192.168.74.251
  elif [ "$1" = "3" ]; then
    ssh -p 2222 ray@192.168.74.251
  fi 
}


if [ $# = 0 ]; then
  print_usage
  exit
fi

COMMAND=$1

case $COMMAND in
  --help|-h)
    if [ $2 = "scp" ]; then
      echo "scp help"
    else
      print_usage
    fi
    exit
    ;;
  port)
    if [ $# = 1 ]; then
      sudo netstat -tulp
    else
      sudo netstat -tulp | grep "$2"
	fi
	exit
    ;;

  0|1|2|3)
    ssh_server $1
    exit
    ;;
esac
    
