#!/bin/bash
# this is ava!

function print_usage(){
  echo "ava 1 # 0, 1, 2, 3"
  echo "ava push"
  echo "ava own"
  echo "ava start"
  echo "ava stop"
  echo "ava show"
  echo "ava memo"
}

function ssh_server(){
  if [[ $1 == "0" ]]; then
  	ssh ray@123.57.54.83
  elif [[ $1 == "1" ]]; then
    ssh -p 2220 ray@192.168.74.251
  elif [[ $1 == "2" ]]; then
  	ssh -p 2221 ray@192.168.74.251
  elif [[ $1 == "3" ]]; then
    ssh -p 2222 ray@192.168.74.251
  fi
}

############################################

TOMCAT_HOME="/usr/local/tomcat/apache-tomcat-7.0.85"
if [[ -z $HADOOP_HOME ]]; then
  HADOOP_HOME="/usr/local/hadoop"
fi

function start_service(){
  if [[ $1 == "tomcat" ]]; then
    $TOMCAT_HOME/bin/startup.sh
  elif [[ $1 == "hadoop" ]]; then
    $HADOOP_HOME/sbin/start-dfs.sh
  else
    echo "examples:"
    echo "ava start tomcat"
    echo "ava start hadoop"
    exit
  fi

  echo "show port in 2s..."
  sleep 2
  
  for pid in `ps aux | grep $1 | awk '{print $2}'`
    do
      sudo netstat -tulpn | grep $pid
    done
}

function stop_service(){
  if [[ $1 == "tomcat" ]]; then
    $TOMCAT_HOME/bin/shutdown.sh
  elif [[ $1 == "hadoop" ]]; then
    $HADOOP_HOME/sbin/stop-dfs.sh
  else
    echo "examples:"
    echo "ava stop tomcat"
    echo "ava stop hadoop" 
    exit   
  fi
}
############################################

function show_info(){
  case $1 in
    port)
      if [[ -z $2 ]]; then
        sudo netstat -tulpn | less
      else
        echo -e "Proto\tRecv-Q\tSend-Q\tLocal Address\t\tForeign Address\t\tState\tPID/Program name"
        sudo netstat -tulpn | grep "LISTEN" | grep $2

        echo -e "\nUSER\tPID\t%CPU\t%MEM\tVSZ\tRSS\tTTY\tSTA\tSTART\tTIME\tCOMMAND"
        for pid in `sudo netstat -tulpn | grep "LISTEN" | grep $2 | awk '{print $7}' | awk -F "/" '{print $1}'`
          do
            ps aux| grep $pid | grep -v "grep $pid"
          done
      fi
      ;;
    app)
      if [[ -z $2 ]]; then
        ps aux | less
      else
        echo -e "USER\tPID\t%CPU\t%MEM\tVSZ\tRSS\tTTY\tSTA\tSTART\tTIME\tCOMMAND"
        ps aux | grep $2 | grep -v "grep $2" | grep -v "show app $2"

        echo -e "\nProto\tRecv-Q\tSend-Q\tLocal Address\t\tForeign Address\t\tState\tPID/Program name"
        for pid in `ps aux | grep $2 | awk '{print $2}'`
          do
            sudo netstat -tulpn | grep $pid
          done
      fi
      ;;
    size)
      if [[ -z $2 ]]; then
        df -h
      elif [[ -d $2 ]]; then
        du -hs $2
      elif [[ -f $2 ]]; then 
        ls -lh $2 | awk '{print $5}'
      fi
      ;;
    cpu|mem)
      cat /proc/cpuinfo
      cat /proc/meminfo
      ;;     
    *)
      echo "examples:"
      echo "ava show port 8080"
      echo "ava show app java"
      echo "ava show size file_or_folder"
      echo "ava show cpu/mem"
  esac
}

############################################
############################################
############################################


if [[ $# == 0 ]]; then
  print_usage
  exit
fi

COMMAND=$1

case $COMMAND in
  0|1|2|3)
    ssh_server $1
    exit
    ;;
  start)
    start_service $2
    exit
    ;;
  stop)
    stop_service $2
    exit
    ;;
  push)
    git pull
    git add -A
    git commit -m "commit"
    git push origin master
    echo "git pull-add-commit-push"
    exit
    ;;
  own)
    sudo chown -R $USER:$USER $PWD
    echo "sudo chown -R $USER:$USER $PWD"
    exit
    ;;
  show)
    if [[ $# == 1 ]]; then
      show_info -h
    else
      show_info "${@:2}"
    fi
    exit
    ;;  
  memo)
    echo "git remote set-url origin git@github.com:hku/ava.git"
    echo "scp -P 2220 ~/.ssh/id_rsa.pub ray@192.168.74.251:~/moon.pub"
    echo "watch -n 1 top"
    echo "jps"
    exit
    ;;
esac