#!/bin/bash

function print_usage(){
  echo "ava 1 # 0, 1, 2, 3"
  echo "ava push"
  echo "ava own"
  echo "ava port"
  echo "ava ps"
  echo "ava help"
}

function ssh_server(){
  if [[ $1 == "0" ]]; then
  	ssh ray@123.57.54.83
  elif [[ $1 == "1" ]]; then
    ssh -p 2220 ray@192.168.74.251
  elif [[ $1 == "2" ]]; then
  	ssh -p 2221 ray@192.168.74.251
  elif [[ $1 == "3" ]]; then
    ssh -p 2222 ray@192.168.74.251
  fi 
}

function start_service(){
  if [[ $1 == "tomcat" ]]; then
    TOMCAT_HOME="/usr/local/tomcat/apache-tomcat-7.0.85"
    $TOMCAT_HOME/bin/startup.sh
  fi
}


if [[ $# == 0 ]]; then
  print_usage
  exit
fi

COMMAND=$1

case $COMMAND in
  0|1|2|3)
    ssh_server $1
    exit
    ;;
  start)
    start_service $2
    exit
    ;;
  push)
    git pull
    git add -A
    git commit -m "commit"
    git push origin master
    echo "git pull-add-commit-push"
    exit
    ;;
  own)
    sudo chown -R $USER:$USER $PWD
    echo "sudo chown -R $USER:$USER $PWD"
    exit
    ;;
  port)
    if [[ $# == 1 ]]; then
      sudo netstat -tulpn | less
    else
      sudo netstat -tulpn | egrep "Local Address|"$2
	  fi
    exit
    ;;
  ps)
    if [[ $# == 1 ]]; then
      ps aux | less
    else
      ps aux| egrep "PID|"$2
    fi
    exit
    ;;   
  help|-h)
    if [[ $2 == "scp" ]]; then
      echo "scp -P 2220 ~/.ssh/id_rsa.pub ray@192.168.74.251:~/moon.pub"
    elif [[ $2 == "info" ]]; then
      echo "cat /proc/cpuinfo"
      echo "cat /proc/meminfo"
      echo "watch -n 1 top"
      echo "df -h"
      echo "ls -lh"
      echo "du -hs /path/to/directory"
      echo "jps"
    else
      print_usage
    fi
    exit
    ;;
esac